language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  
before_install:
  - cp databata-engine/gradle.properties.sample databata-engine/gradle.properties
  
notifications:
  email:
    on_success: change
    on_failure: always
